<?php
// Generated by Zend Framework 2
return array(
    'UthandoThemeManager\Module'                      => __DIR__ . '/Module.php',
    'UthandoThemeManager\Event\MvcListener'           => __DIR__ . '/src/UthandoThemeManager/Event/MvcListener.php',
    'UthandoThemeManager\Options\ThemeOptions'        => __DIR__ . '/src/UthandoThemeManager/Options/ThemeOptions.php',
    'UthandoThemeManager\Service\ThemeOptionsFactory' => __DIR__ . '/src/UthandoThemeManager/Service/ThemeOptionsFactory.php',
    'UthandoThemeManager\View\BootStrapTheme'         => __DIR__ . '/src/UthandoThemeManager/View/BootStrapTheme.php',
    'UthandoThemeManager\View\ThemePath'              => __DIR__ . '/src/UthandoThemeManager/View/ThemePath.php',
);