<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoThemeManager\Controller\Settings'         => __DIR__ . '/src/UthandoThemeManager/Controller/Settings.php',
    'UthandoThemeManager\View\BootStrapTheme'         => __DIR__ . '/src/UthandoThemeManager/View/BootStrapTheme.php',
    'UthandoThemeManager\View\ThemeOptionsHelper'     => __DIR__ . '/src/UthandoThemeManager/View/ThemeOptionsHelper.php',
    'UthandoThemeManager\View\SocialLinks'            => __DIR__ . '/src/UthandoThemeManager/View/SocialLinks.php',
    'UthandoThemeManager\View\ThemePath'              => __DIR__ . '/src/UthandoThemeManager/View/ThemePath.php',
    'UthandoThemeManager\Options\ThemeOptions'        => __DIR__ . '/src/UthandoThemeManager/Options/ThemeOptions.php',
    'UthandoThemeManager\Service\ThemeOptionsFactory' => __DIR__ . '/src/UthandoThemeManager/Service/ThemeOptionsFactory.php',
    'UthandoThemeManager\Event\MvcListener'           => __DIR__ . '/src/UthandoThemeManager/Event/MvcListener.php',
    'UthandoThemeManager\Model\WidgetGroup'           => __DIR__ . '/src/UthandoThemeManager/Model/WidgetGroup.php',
    'UthandoThemeManager\Model\Widget'                => __DIR__ . '/src/UthandoThemeManager/Model/Widget.php',
    'UthandoThemeManager\Module'                      => __DIR__ . '/Module.php',
    'UthandoThemeMangerTest\Framework\TestCase'       => __DIR__ . '/test/UthandoThemeManagerTest/Framework/TestCase.php',
    'UthandoThemeManagerTest\Bootstrap'               => __DIR__ . '/test/Bootstrap.php',
);
