<?php $this->headTitle('Widget Groups') ?>
<?php $this->layout()->pageTitle = $this->translate('Widget Groups');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<a href="<?=$this->url('admin/theme-manager/settings');?>" data-toggle="tooltip" title="<?=$this->translate('Settings');?>" class="btn btn-primary">
    <i class="fa fa-cog"></i>
</a>
<a href="<?=$this->url('admin/theme-manager/widget-group/edit', [
    'action' => 'add'
]);?>" type="submit" data-toggle="tooltip" title="<?=$this->translate('Add Widget Group');?>" class="btn btn-primary">
    <i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('Widget List');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'widget-group',
            'searchInputs'	=> [
                $this->translate('Widget Group') => 'name',
            ],
        ]);?>
    </div>
    <div id="table-widget-group" class="admin-table">
        <?=$this->partial('uthando-theme-manager/widget-group/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('#table-widget-group').dataGrid({
            url : 'widget-group/list',
            query: { sort : 'widgetGroupId' },
            searchForm : $('#search-widget-group'),
            paging : 'links',
            columnSort: true
        });
    });
</script>
